### ISSUE TITLE
Error: Could not find or load main class playground.Playground

### ISSUE THREAD

**Issue by Allenhanbo** [rockthejvm/spark-essentials#1]
After I git clone the spark-essentials folder. I open the folder in sbt using intellij. But when I tried to run the Playground.scala file. I meet the problem. I don't know why I will have this issue.

**Comment by daniel-ciocirlan** [comment]
The problem is in IntelliJ - go to Project Structure, then SDKs, then remove the JDK there and add it back. It usually solves the problem.

That, or simply restarting IntelliJ also solves it for some people.

**Comment by subhan98** [comment]
Hi Daniel, i did the same as above mentioned but still unable to get my first code working.
<img width="1439" alt="Screenshot 2021-09-30 at 15 26 18" src="https://user-images.githubusercontent.com/41581109/135474174-62fdf3f0-702f-4628-b5b9-3ca4b574836c.png">
<img width="1170" alt="Screenshot 2021-09-30 at 15 30 24" src="https://user-images.githubusercontent.com/41581109/135474964-b113cd2e-2647-455d-974b-ddaaff59124f.png">

**Comment by daniel-ciocirlan** [comment]
Try to remove the JDK and add it back. It almost always solves the problem.

**Comment by subhan98** [comment]
Hi daniel, i have followed the above instruction (removed all the java versions and then added java 1.8.0._202. and restarted IntelliJ) but still the same.

**Comment by daniel-ciocirlan** [comment]
What's your Java version (in the Project Structure - SDKs) and your Scala version (in build.sbt and in Project Structure - Global Libraries) ?

**Comment by subhan98** [comment]
The java version i am using is 1.8.0_202 :

<img width="1018" alt="Screenshot 2021-10-24 at 22 04 20" src="https://user-images.githubusercontent.com/41581109/138612855-9e7a958f-e828-49b5-b0be-fac0589bcdac.png">
The scala version is 2.13.1 :

<img width="1041" alt="Screenshot 2021-10-24 at 22 06 01" src="https://user-images.githubusercontent.com/41581109/138612925-114119d8-9bef-4752-aa05-87f807ebd126.png">

**Comment by subhan98** [comment]
The scala version in build.sbt is the same 2.13.1
<img width="1055" alt="Screenshot 2021-10-24 at 22 07 07" src="https://user-images.githubusercontent.com/41581109/138612967-9ef5d801-614c-4bcc-9cdd-7a729a8b8110.png">

**Comment by daniel-ciocirlan** [comment]
I think you have too many JDKs 😄 remove all but the first one, restart IntelliJ, and try again - if it still doesn't work, let me know.

**Comment by subhan98** [comment]
Hi Daniel, i removed all the JDKs except the required one but still the same problem. 
I deleted the repo and recloned it. It is working now. Thanks for your prompt responses.

**Comment by jjcfrancisco** [comment]
I had the same issues as subhan98 but after deleting repo and recloning, it worked.

**Comment by ebansal15** [comment]
Hi daniel, i am following your scala3 course, i m having the same issue. unable to load or find class, i have cloned it many times still getting the error.

**Comment by daniel-ciocirlan** [comment]
Check:
- JDK version
- whether SBT downloads the libraries

**Comment by ujjaldey** [comment]
I was facing the same issue. I just closed and deleted the project from IntelliJ, and then reimported the directory as a new project in IntelliJ. It started working!
