### ISSUE TITLE
Error response from daemon: pull access denied for spark-worker, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by Up2skY-a** [rockthejvm/spark-essentials#20]
Hello, a have a problem with Docker.
![2023-12-14_23-53-05](https://github.com/rockthejvm/spark-essentials/assets/150068896/34f0062a-6de9-49cc-90d0-6dbb1257a6c9)

**Comment by daniel-ciocirlan** [comment]
Closing this on GitHub, let's talk on our internal Slack.
