### ISSUE TITLE
Cannot build Spark cluster

### ISSUE THREAD

**Issue by un4ckn0wl3z** [rockthejvm/spark-essentials#7]
Help me bro, I cannot build spark-cluster.

**Comment by un4ckn0wl3z** [comment]
downloading https://repo1.maven.org/maven2/com/github/cb372/scalacache-core_2.12/0.20.0/scalacache-core_2.12-0.20.0.jar ...
[SUCCESSFUL ] com.github.cb372#scalacache-core_2.12;0.20.0!scalacache-core_2.12.jar (685ms)
downloading https://repo1.maven.org/maven2/com/github/ben-manes/caffeine/caffeine/2.5.6/caffeine-2.5.6.jar ...
[SUCCESSFUL ] com.github.ben-manes.caffeine#caffeine;2.5.6!caffeine.jar (769ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d446488ff6832/ivy-2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d
446488ff6832.jar ...
[SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-cb9cc189e9f3af519f9f102e6c5d446488ff6832!ivy.jar (784ms)
:: retrieving :: org.scala-sbt#boot-app
confs: [default]
80 artifacts copied, 0 already retrieved (28561kB/185ms)
Getting Scala 2.12.7 (for sbt)...
:: retrieving :: org.scala-sbt#boot-scala
confs: [default]
5 artifacts copied, 0 already retrieved (19715kB/33ms)
[warn] No sbt.version set in project/build.properties, base directory: /
[info] Set current project to root (in build file:/)
[info] 1.2.8
Removing intermediate container 673fc328073c
 ---> 2d87e45ae7c1
Step 16/17 : RUN wget --no-verbose http://apache.mirror.iphh.net/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz && tar -x
vzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz       && mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} spark       && rm spark-${SPARK_VERS
ION}-bin-hadoop${HADOOP_VERSION}.tgz
 ---> Running in 14318627bd73
The command '/bin/sh -c wget --no-verbose http://apache.mirror.iphh.net/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz &&
 tar -xvzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz       && mv spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} spark       && rm spark-${SPA
RK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz' returned a non-zero code: 4

**Comment by daniel-ciocirlan** [comment]
Did the Spark download fail? I can't tell from the output.
